// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeq6QeE8xe6xmg1BdW0lkMvHZ7FeJlSWw',
    appId: '1:186544637938:web:2bf54c0ae88c4c3710cd6b',
    messagingSenderId: '186544637938',
    projectId: 'foodmyproject',
    authDomain: 'foodmyproject.firebaseapp.com',
    storageBucket: 'foodmyproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLCDrSBv1mKgRPjKym4IoOUtwhEIkkMw',
    appId: '1:186544637938:android:54af8f5ed5a1f21d10cd6b',
    messagingSenderId: '186544637938',
    projectId: 'foodmyproject',
    storageBucket: 'foodmyproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1EAHKOmEgEX1-7csti5zSHnyAVLs-G14',
    appId: '1:186544637938:ios:42582a1db9a8b0a210cd6b',
    messagingSenderId: '186544637938',
    projectId: 'foodmyproject',
    storageBucket: 'foodmyproject.appspot.com',
    iosBundleId: 'com.example.foodMyProject',
  );
}
